### ISSUE TITLE
trinity - Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#1933]
LinuxBrew, RHEL 7.1 - might be a master homebrew problem, not science? Java?

```
==> Installing trinity from homebrew/homebrew-science
==> Installing dependencies for trinity: bowtie, bamtools, express
==> Installing trinity dependency: bowtie
==> Downloading https://github.com/BenLangmead/bowtie/archive/v1.1.1.tar.gz
######################################################################## 100.0%
==> make allall
/home/linuxbrew/Cellar/bowtie/1.1.1: 95 files, 38M, built in 46 seconds
==> Installing trinity dependency: bamtools
==> Downloading https://github.com/pezmaster31/bamtools/archive/v2.3.0.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/sjackman/bamtools/commit/3b6b89d.diff
######################################################################## 100.0%
==> Patching
patching file src/api/CMakeLists.txt
==> cmake .. -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/Cellar/bamtools/2.3.0 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST
==> make install
/home/linuxbrew/Cellar/bamtools/2.3.0: 26 files, 2.8M, built in 13 seconds
==> Installing trinity dependency: express
==> Downloading http://bio.math.berkeley.edu/eXpress/downloads/express-1.5.1/express-1.5.1-src.tgz
######################################################################## 100.0%
==> cmake . -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/Cellar/express/1.5.1 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -
==> make install
/home/linuxbrew/Cellar/express/1.5.1: 4 files, 1.8M, built in 21 seconds
==> Installing trinity
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/linuxbrew/Library/Homebrew/requirements/java_dependency.rb:11:in `initialize'
/home/linuxbrew/Library/Homebrew/requirements/java_dependency.rb:11:in `new'
/home/linuxbrew/Library/Homebrew/requirements/java_dependency.rb:11:in `block in <class:JavaDependency>'
/home/linuxbrew/Library/Homebrew/requirement.rb:76:in `instance_eval'
/home/linuxbrew/Library/Homebrew/requirement.rb:76:in `modify_build_environment'
/usr/share/ruby/set.rb:232:in `each_key'
/usr/share/ruby/set.rb:232:in `each'
/home/linuxbrew/Library/Homebrew/dependencies.rb:68:in `each'
/home/linuxbrew/Library/Homebrew/build.rb:98:in `install'
/home/linuxbrew/Library/Homebrew/build.rb:185:in `<main>'
```

**Comment by iml** [comment]
Ah, the new Java requirement is more Mac-oriented now (see https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/java_dependency.rb#L30). I guess we should just remove that dependency since it's not used at buildtime and Trinity already has built-in warnings to deal with Java.
