### ISSUE TITLE
Diamond Build Failure: 

### ISSUE THREAD

**Issue by LeeBergstrand** [Homebrew/homebrew-science#2347]
```shell
brew install diamond
==> Installing diamond from homebrew/homebrew-science
==> Downloading https://github.com/bbuchfink/diamond/archive/v0.7.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/diamond-0.7.7.tar.gz
==> make
g++ -O3 -DNDEBUG -I/usr/local/Cellar/boost/1.58.0/include -Wall -Wno-uninitialized -march=native -c -o main.o main.cpp
/usr/local/Library/ENV/4.3/g++:320:in `exec': no implicit conversion of nil into String (TypeError)
	from /usr/local/Library/ENV/4.3/g++:320:in `<main>'
make: *** [main.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
```

**Comment by LeeBergstrand** [comment]
updated home-brew and error is now different?

```shell
brew install diamond
==> Installing diamond from homebrew/homebrew-science
==> Downloading https://github.com/bbuchfink/diamond/archive/v0.7.7.tar.gz
Already downloaded: /Library/Caches/Homebrew/diamond-0.7.7.tar.gz
==> make
      vtable for boost::program_options::typed_value<unsigned long long, char> in main.o
      vtable for boost::program_options::typed_value<int, char> in main.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [diamond] Error 1
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x007f9d1a89e5b8>::Diamond (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure
```

**Comment by tdsmith** [comment]
Per the troubleshooting link, can you share `brew gist-logs diamond` please?

**Comment by LeeBergstrand** [comment]
My apologies... 

https://gist.github.com/anonymous/a9cefd97253ecd9b4368

**Comment by tdsmith** [comment]
Oh, I see. C++ code compiled by clang isn't compatible with C++ code compiled by gcc. Until we support using clang-omp from Homebrew or omp support is baked into Xcode's clang, you'll have to rebuild boost with gcc in order to use this formula. (After you do that, anything that uses boost will have to be rebuilt with gcc.) Sorry!

**Comment by tdsmith** [comment]
Let us know if we can help with anything.
