### ISSUE TITLE
Mac OSX 10.10.5: bedtools won't install

### ISSUE THREAD

**Issue by deannachurch** [Homebrew/homebrew-science#2729]
bedtools seems to have some issues:

````
brew search bedtools
bedtools
[10Sep 22:27:44 l-mp-dchurch1 source]$ brew install bedtools
Error: /usr/local/Library/Formula/bedtools.rb:4: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/usr/local/Library/Formula/bedtools.rb:5: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/usr/local/Library/Formula/bedtools.rb:5: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:197:in `factory'
/usr/local/Library/Homebrew/formulary.rb:342:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:127:in `<main>'
````
All other things seem good:
````
[10Sep 22:20:17 l-mp-dchurch1 source]$ brew update
Already up-to-date.
[10Sep 22:20:30 l-mp-dchurch1 source]$ brew doctor
Your system is ready to brew.
````

**Comment by deannachurch** [comment]
Note: I tried
````
brew gist-logs bedtools
````

but got no link

**Comment by dunn** [comment]
What's the output of `brew cat bedtools`?

**Comment by deannachurch** [comment]
similar to above:
````
brew cat bedtools
Error: /usr/local/Library/Formula/bedtools.rb:4: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/usr/local/Library/Formula/bedtools.rb:5: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/usr/local/Library/Formula/bedtools.rb:5: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:197:in `factory'
/usr/local/Library/Homebrew/formulary.rb:342:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/cat.rb:9:in `cat'
/usr/local/Library/brew.rb:127:in `<main>'
````

**Comment by tdsmith** [comment]
It's strange that /usr/local/Library/Formula/bedtools.rb exists (it should not) and that it contains HTML (it should not). Can you try running `rm -f /usr/local/Library/Formula/*` and `cd /usr/local && git reset --hard master`?

**Comment by deannachurch** [comment]
I tried this, but it seemed to have no impact:
````
[10Sep 23:25:06 l-mp-dchurch1 ~]$ rm -f /usr/local/Library/Formula/*
[11Sep 05:30:21 l-mp-dchurch1 ~]$ cd /usr/local && git reset --hard master
HEAD is now at b00ce67 thefuck: update 3.0 bottle.
[11Sep 05:30:34 l-mp-dchurch1 local]$ cd
[11Sep 05:30:42 l-mp-dchurch1 ~]$ brew search bedtools
No formula found for "bedtools".
==> Searching pull requests...
Closed pull requests:
bedtools 2.15.0 (https://github.com/Homebrew/homebrew/pull/9451)
Updated bedtools formula to 2.17.0 (https://github.com/Homebrew/homebrew/pull/15842)
bedtools 2.16.2 (https://github.com/Homebrew/homebrew/pull/11456)
bedtools 2.16.1 (https://github.com/Homebrew/homebrew/pull/10927)
bedtools 2.14.3 (https://github.com/Homebrew/homebrew/pull/8482)
bedtools 2.13.4 (https://github.com/Homebrew/homebrew/pull/8314)
bedtools 2.13.3 (https://github.com/Homebrew/homebrew/pull/7958)
bedtools 2.13.2 (https://github.com/Homebrew/homebrew/pull/7839)
new formula:   Library/Formula/bedtools.rb (https://github.com/Homebrew/homebrew/pull/5152)
[11Sep 05:30:52 l-mp-dchurch1 ~]$ brew tap homebrew/science
Warning: Already tapped!
[11Sep 05:31:05 l-mp-dchurch1 ~]$ brew info bedtools
Error: /Library/Caches/Homebrew/Formula/bedtools.rb:4: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Library/Caches/Homebrew/Formula/bedtools.rb:5: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Library/Caches/Homebrew/Formula/bedtools.rb:5: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:197:in `factory'
/usr/local/Library/Homebrew/formulary.rb:342:in `find_with_priority'
/usr/local/Library/Homebrew/cmd/info.rb:35:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:127:in `<main>'
````

**Comment by xu-cheng** [comment]
Please try:
```bash
rm -rf /Library/Caches/Homebrew/Formula/
brew untap homebrew/science
brew tap homebrew/science
```

**Comment by deannachurch** [comment]
That seemed to do the trick- it does look like the first install was incomplete:
````
[11Sep 06:00:49 l-mp-dchurch1 ~]$ brew untap homebrew/science
Untapping homebrew/science... (1320 files, 16M)
Untapped 223 formulae
[11Sep 06:00:59 l-mp-dchurch1 ~]$ brew tap homebrew/science
==> Tapping homebrew/science
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 555, done.
remote: Compressing objects: 100% (553/553), done.
remote: Total 555 (delta 2), reused 70 (delta 1), pack-reused 0
Receiving objects: 100% (555/555), 436.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
Tapped 548 formulae (575 files, 2.9M)
````

Now I can find:
````
brew info bedtools
homebrew/science/bedtools: stable 2.24.0 (bottled), HEAD
bedtools: A powerful toolset for genome arithmetic
https://github.com/arq5x/bedtools2
Not installed
From: https://github.com/Homebrew/homebrew-science/blob/master/bedtools.rb
````

**Comment by deannachurch** [comment]
Thanks to all for your help! Desperation is not being able to brew bedtools!

**Comment by dpo** [comment]
Feel free to close the issue if it's been resolved to your satisfaction.

**Comment by deannachurch** [comment]
I think things are good- thanks!
