### ISSUE TITLE
Neuron brew fails to install correctly in python virtualenv

### ISSUE THREAD

**Issue by wvangeit** [Homebrew/homebrew-science#2810]
The installation of the Neuron brew has issues when it is installed in a python virtualenv.
You can find a trace of such an installation below.

The core issue is that virtualenv doesn't support the site.getusersitepackages() call. I've also created an issue in the virtualenv repo:
https://github.com/pypa/virtualenv/issues/804

I wonder if a workaround could be create from the side of the homebrew package.

(virtualenv version: 13.1.2)

└──> brew install neuron
==> Installing neuron from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles-science/neuron-7.4.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/neuron-7.4.yosemite.bottle.tar.gz
==> Pouring neuron-7.4.yosemite.bottle.tar.gz
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
==> Caveats
NEURON recommends that you set an X11 option that raises the window
under the mouse cursor on mouseover. If you don't set this option,
NEURON's GUI will still work, but you will have to click in each window
before you can interact with the widgets in that window.

To raise the window on mouse hover, execute:
    defaults write org.macosforge.xquartz.X11 wm_ffm -bool true
To revert this behavior, execute:
    defaults write org.macosforge.xquartz.X11 wm_ffm -bool false

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p 
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> homebrew.pth
==> Summary
🍺  /usr/local/Cellar/neuron/7.4: 418 files, 16M

**Comment by wvangeit** [comment]
Fyi, a gist with more debugging info:
https://gist.github.com/wvangeit/9793efdb6bb0fd92b010
