### ISSUE TITLE
opencv3 PYTHON_PATH and other variables set incorrectly in some cases

### ISSUE THREAD

**Issue by ahundt** [Homebrew/homebrew-science#2846]
I'm trying to build opencv3 with linuxbrew with the standalone setup, and it seems to be failing. I've recorded the relevant [gist-logs](https://gist.github.com/ee4c3b3ce43b67eedc82).

To reproduce the error from scratch create a vanilla ubuntu installation (I was using a VM with vmware tools) and run the following script from [ahundt/homebrew-robotics](https://github.com/ahundt/homebrew-robotics) which automates the linuxbrew setup and goes through opencv3 installation:

```
bash <(curl -fsSL https://raw.githubusercontent.com/ahundt/homebrew-robotics/master/robonetracker.sh)
```

The opencv3 step of the above script is failing, here is the error:

```
[100%] Built target opencv_test_stitching
[100%] Linking CXX executable ../../bin/opencv_perf_stitching
cd /tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild/modules/stitching && /home/hbr/.linuxbrew/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/opencv_perf_stitching.dir/link.txt --verbose=1
/home/hbr/.linuxbrew/bin/g++-5  -std=c++11  -Os -w -pipe -march=core2    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden   -DNDEBUG   -L/home/hbr/.linuxbrew/lib -Wl,--dynamic-linker=/home/hbr/.linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 -Wl,-rpath,/home/hbr/.linuxbrew/lib    CMakeFiles/opencv_perf_stitching.dir/perf/perf_main.cpp.o CMakeFiles/opencv_perf_stitching.dir/perf/opencl/perf_warpers.cpp.o CMakeFiles/opencv_perf_stitching.dir/perf/opencl/perf_stitch.cpp.o CMakeFiles/opencv_perf_stitching.dir/perf/perf_stich.cpp.o  -o ../../bin/opencv_perf_stitching -rdynamic ../../lib/libopencv_ts.a ../../lib/libopencv_stitching.so.3.0.0 ../../lib/libopencv_hal.a ../../lib/libopencv_hal.a ../../lib/libopencv_hal.a ../../lib/libopencv_objdetect.so.3.0.0 ../../lib/libopencv_xfeatures2d.so.3.0.0 -ldl -lm -lpthread -lrt ../../../3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64/libippicv.a ../../lib/libopencv_shape.so.3.0.0 ../../lib/libopencv_video.so.3.0.0 ../../lib/libopencv_calib3d.so.3.0.0 ../../lib/libopencv_features2d.so.3.0.0 ../../lib/libopencv_flann.so.3.0.0 ../../lib/libopencv_ml.so.3.0.0 ../../lib/libopencv_highgui.so.3.0.0 ../../lib/libopencv_videoio.so.3.0.0 ../../lib/libopencv_imgcodecs.so.3.0.0 ../../lib/libopencv_imgproc.so.3.0.0 ../../lib/libopencv_core.so.3.0.0 ../../lib/libopencv_hal.a -ldl -lm -lpthread -lrt ../../../3rdparty/ippicv/unpack/ippicv_lnx/lib/intel64/libippicv.a -Wl,-rpath,/home/hbr/.linuxbrew/Cellar/opencv3/3.0.0/lib 
make[2]: Leaving directory '/tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild'
[100%] Built target opencv_perf_stitching
make[2]: Leaving directory '/tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild'
CMakeFiles/Makefile2:13078: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/all' failed
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: Leaving directory '/tmp/opencv320151007-88137-d43df3/opencv-3.0.0/macbuild'
Makefile:152: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

```

**Comment by ahundt** [comment]
@mshabunin has [narrowed down the issue](https://github.com/Itseez/opencv/issues/5482#issuecomment-147405076), apparently the python dependency isn't installed or the path to it isn't correct.

**Comment by ahundt** [comment]
It seems python 2.7 is configuring correctly, but 3.4 is failing:


```
-- Found PythonInterp: /home/hbr/.linuxbrew/bin/python (found suitable version "2.7.10", minimum required is "2.7") 
-- Found PythonLibs: /libpython2.7.so (found suitable exact version "2.7.10") 
-- Found PythonInterp: /usr/bin/python3.4 (found suitable version "3.4", minimum required is "3.4") 
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "3.4.0")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hbr/.linuxbrew/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/home/hbr/.linuxbrew/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/hbr/.linuxbrew/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/hbr/.linuxbrew/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/hbr/.linuxbrew/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: dynamic module does not define init function (PyInit_multiarray) 
```

**Comment by ahundt** [comment]
At least one problem is the python3 lines equivalent to these python2 lines are missing from [opencv3.rb](https://github.com/Homebrew/homebrew-science/blob/master/opencv3.rb):

```
      py_lib = OS.linux? ? `python-config --configdir`.chomp : "#{py_prefix}/lib"
```

**Comment by ahundt** [comment]
Here are some of the problems with the opencv3.rb script explained in more detail:
https://github.com/Itseez/opencv/issues/5482#issuecomment-147533982

**Comment by tdsmith** [comment]
A PR for this would be great if you have time to suggest a fix.

**Comment by iMichka** [comment]
This issue is fairly outdated. There were multiple changes to the opencv3 formula since the initial report. I'm closing this issue, please open a new issue with updated information if you still encounter problems. Thanks.
