### ISSUE TITLE
hdf5 install failure - undefined method 'fortran?'

### ISSUE THREAD

**Issue by oliveoyl** [Homebrew/homebrew-science#3079]
I get the following error when trying to install hdf5. I am unsure of the solution. I have updated Xcode, developer tools, and homebrew. Does anyone know what is happening?

brew install hdf5
==> Downloading http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.9/src/hdf5-1.8.9.ta
Already downloaded: /Library/Caches/Homebrew/hdf5-1.8.9.tar.bz2
Error: undefined method `fortran?' for #<Formula hdf5 (stable) /usr/local/Library/Formula/hdf5.rb>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/hdf5.rb:26:in `install'
/usr/local/Library/Homebrew/build.rb:130:in `block in install'
/usr/local/Library/Homebrew/formula.rb:919:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1532:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1523:in `stage'
/usr/local/Library/Homebrew/formula.rb:915:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'

**Comment by oliveoyl** [comment]
re-installed brew and it worked.
