### ISSUE TITLE
Graph-Tool - libgmp versioning

### ISSUE THREAD

**Issue by tschellenbach** [Homebrew/homebrew-science#3174]
After installing via brew install graph-tool I get the following error when importing graph_tool.all:

```
/usr/local/lib/python2.7/site-packages/graph_tool/all.py:40: RuntimeWarning: Error importing draw module, proceeding nevertheless: dlopen(/usr/local/lib/python2.7/site-packages/graph_tool/generation/libgraph_tool_generation.so, 8): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/graph_tool/generation/libgraph_tool_generation.so
  Reason: Incompatible library version: libgraph_tool_generation.so requires version 14.0.0 or later, but libgmp.10.dylib provides version 13.0.0
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import graph_tool.all as gt
  File "/usr/local/lib/python2.7/site-packages/graph_tool/all.py", line 44, in <module>
    from graph_tool.generation import *
  File "/usr/local/lib/python2.7/site-packages/graph_tool/generation/__init__.py", line 53, in <module>
    dl_import("from . import libgraph_tool_generation")
  File "/usr/local/lib/python2.7/site-packages/graph_tool/dl_import.py", line 57, in dl_import
    exec(import_expr, local_dict, global_dict)
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/graph_tool/generation/libgraph_tool_generation.so, 8): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/graph_tool/generation/libgraph_tool_generation.so
  Reason: Incompatible library version: libgraph_tool_generation.so requires version 14.0.0 or later, but libgmp.10.dylib provides version 13.0.0
```

No luck resolving this so far.

**Comment by dpo** [comment]
`brew upgrade gmp`.

**Comment by tschellenbach** [comment]
Running brew upgrade gmp tells me:

```
>>> brew upgrade gmp
gmp 6.0.0a already installed
```

I also tried

```
>>> brew uninstall gmp
>>> brew install gmp
```

But I get the same error

**Comment by dpo** [comment]
Seems like you need to `brew update; brew uninstall -f gmp; brew install gmp`.

**Comment by tschellenbach** [comment]
```brew update; brew uninstall -f gmp; brew install gmp
brew uninstall -f libpng; brew install libpng```

Did the trick, thanks so much for the help! It does still show a warning:

```
WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
```

But I suppose that's harmless.

**Comment by dpo** [comment]
I've no idea. Please reopen if there are problems.
