### ISSUE TITLE
Pymol does not start (similar to #3113)

### ISSUE THREAD

**Issue by RamRS** [Homebrew/homebrew-science#3299]
I installed pymol using
`$brew install pymol`

When I run
`$pymol` or `$pymol -M`

I see
```
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 71, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 521, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/_cmd.so, 2): Library not loaded: /opt/X11/lib/libpng15.15.dylib
  Referenced from: /usr/local/Cellar/pymol/1.7.6.0_1/libexec/lib/python2.7/site-packages/pymol/_cmd.so
  Reason: Incompatible library version: _cmd.so requires version 39.0.0 or later, but libpng15.15.dylib provides version 34.0.0
```

I have tried setting `DYLIB_PATH` to where `libpng16.dylib` is located (which I found using `locate libpng16.dylib`), but that does not help.

**Comment by Moisan** [comment]
This is a duplicate of #3134 .

**Comment by RamRS** [comment]
Sorry, I should have searched before opening a new issue. XQuartz version was the problem. Also, TIL XQuartz is X11.
