### ISSUE TITLE
gubbins - Failed to import the site module (since python 3.4 -> 3.5)

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#3490]
I upgraded from Brew python 3.4 to 3.5 and now gubbins doesn't install.

Any idea why the backtrace ends up in python2.7 ?

CC: @andrewjpage 

```
==> python3 -c import setuptools... --no-user-cfg install --prefix=/bio/linuxbrew/Cellar/gubbins/1.4.7/libexec/ven
dor --single-version-externally-managed --record=installed.txt
Failed to import the site module
Error processing line 1 of /bio/linuxbrew/Cellar/python3/3.5.1/lib/python3.5/site-packages/matplotlib-1.5.1-py3.5-nspkg.pth:

Traceback (most recent call last):
  File "/bio/linuxbrew/bin/../Cellar/python3/3.5.1/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/bio/linuxbrew/Cellar/python3/3.5.1/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/bio/linuxbrew/Cellar/python3/3.5.1/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/bio/linuxbrew/Cellar/python3/3.5.1/lib/python3.5/collections/__init__.py", line 16, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/bio/linuxbrew/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bio/linuxbrew/bin/../Cellar/python3/3.5.1/lib/python3.5/site.py", line 563, in <module>
    main()
  File "/bio/linuxbrew/bin/../Cellar/python3/3.5.1/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/bio/linuxbrew/bin/../Cellar/python3/3.5.1/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/bio/linuxbrew/bin/../Cellar/python3/3.5.1/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/bio/linuxbrew/bin/../Cellar/python3/3.5.1/lib/python3.5/site.py", line 177, in addpackage
    import traceback
  File "/bio/linuxbrew/Cellar/python3/3.5.1/lib/python3.5/traceback.py", line 3, in <module>
    import collections
  File "/bio/linuxbrew/Cellar/python3/3.5.1/lib/python3.5/collections/__init__.py", line 16, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/bio/linuxbrew/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

**Comment by tseemann** [comment]
Paging author @andrewjpage - any ideas?

**Comment by ShivangiM** [comment]
[http://stackoverflow.com/a/42214539/5511915](url)
