### ISSUE TITLE
madlib test failed against postgresql 9.5.2

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew-science#3501]
With `postgresql` 9.5.2 installed, `brew test madlib` is failing, both for me locally (from source or bottle), and on Jenkins test-bot runs where `madlib` is tested as part of a `postgresql` formula change. Looks like it's causing https://github.com/Homebrew/legacy-homebrew/pull/49612 to fail in the test stage.

With the current bottle, `postgresql` changes [fail like this](http://bot.brew.sh/job/Legacy%20Homebrew%20Pull%20Requests/44099/) on 10.9 and 10.10. (I'm assuming the 10.11 is passing because its bottle was added after the recent postgresql update?)

```
==> launchctl load /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
==> /usr/local/Cellar/postgresql/9.5.2/bin/createdb -w -U brew test_madpack
==> /usr/local/Cellar/madlib/1.8/bin/madpack -p postgres -c brew/@localhost/test_madpack install
madpack.py : INFO : Detected PostgreSQL version 9.5.
madpack.py : ERROR : This version is not among the PostgreSQL versions for which MADlib support files have been installed (9.4).
==> /usr/local/Cellar/postgresql/9.5.2/bin/dropdb -w -U brew test_madpack
```

When I do `brew install -s madlib` locally on 10.9.5, with a fresh `brew install postgresql --with-python`, I get a failure like this.

```
$ brew test madlib
Testing homebrew/science/madlib
==> Using the sandbox
==> /usr/local/Cellar/madlib/1.8/bin/madpack -h
==> launchctl load /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
==> /usr/local/Cellar/postgresql/9.5.2/bin/createdb -w -U janke test_madpack
Last 15 lines from /Users/janke/Library/Logs/Homebrew/madlib/03.createdb:
2016-04-04 02:41:36 -0400

/usr/local/Cellar/postgresql/9.5.2/bin/createdb
-w
-U
janke
test_madpack

createdb: could not connect to database template1: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
Error: homebrew/science/madlib: failed
Failed executing: /usr/local/Cellar/postgresql/9.5.2/bin/createdb -w -U janke test_madpack
/usr/local/Library/Homebrew/formula.rb:1481:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1418:in `open'
/usr/local/Library/Homebrew/formula.rb:1418:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/madlib.rb:98:in `block in <class:Madlib>'
/usr/local/Library/Homebrew/formula.rb:1327:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:37:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1323:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

I was trying to bump the bottle revision for `madlib` [like here](https://github.com/Homebrew/homebrew-science/commit/c0987ce70c322a12e7643bef06b2bfe9f22ab4b2) because I thought a rebuild against the current `postgresql` would fix it. But I'm getting that other test failure when installing it locally from source so the bottle's not involved.

Anyone know what's going on here?

**Comment by jonchang** [comment]
The tests passed on CI thanks to #4360 so I think that this is now fixed.
