### ISSUE TITLE
Artemis failed to open

### ISSUE THREAD

**Issue by maculatus** [Homebrew/homebrew-science#3623]
Hello,
I installed the new version of artemis a few weeks ago and today it failed to open after the last update. I uninstall and re-install artemis with the same results. I also installed the app-java without a change.

>art
java.lang.RuntimeException: cannot load system cursor: CopyDrop.32x32
	at sun.awt.X11.XToolkit.lazilyLoadDesktopProperty(XToolkit.java:1541)
	at java.awt.Toolkit.getDesktopProperty(Toolkit.java:1803)
	at java.awt.dnd.DragSource.load(DragSource.java:131)
	at java.awt.dnd.DragSource.<clinit>(DragSource.java:148)
	at uk.ac.sanger.artemis.components.FeatureDisplay.<init>(FeatureDisplay.java:426)
	at uk.ac.sanger.artemis.components.FeatureDisplay.<init>(FeatureDisplay.java:328)
	at uk.ac.sanger.artemis.components.EntryEdit.<init>(EntryEdit.java:307)
	at uk.ac.sanger.artemis.components.ArtemisMain$9.run(ArtemisMain.java:739)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.awt.AWTException: Exception: class java.lang.IllegalArgumentException Width (0) and height (0) must be non-zero occurred while creating cursor CopyDrop.32x32
	at java.awt.Cursor.getSystemCustomCursor(Cursor.java:363)
	at sun.awt.X11.XToolkit.lazilyLoadDesktopProperty(XToolkit.java:1539)
	... 21 more
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at uk.ac.sanger.artemis.components.FeatureDisplay.<init>(FeatureDisplay.java:426)
	at uk.ac.sanger.artemis.components.FeatureDisplay.<init>(FeatureDisplay.java:328)
	at uk.ac.sanger.artemis.components.EntryEdit.<init>(EntryEdit.java:307)
	at uk.ac.sanger.artemis.components.ArtemisMain$9.run(ArtemisMain.java:739)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: failed to load system cursor: DnD.Cursor.CopyDrop : cannot load system cursor: CopyDrop.32x32
	at java.awt.dnd.DragSource.load(DragSource.java:135)
	at java.awt.dnd.DragSource.<clinit>(DragSource.java:148)
	... 18 more

**Comment by tseemann** [comment]
@maculatus 
Linux or Mac?
What version of Java?  `java -version`
If Mac, do you have XQuartz installed ?

**Comment by maculatus** [comment]
It is a linux and the java -version:
java version "1.8.0_91"
Java (TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Also, I tried with the openjdk version and same problem.
sudo update-alternatives --config java
password
*/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
/usr/lib/jvm/java-8-oracle/jre/bin/java

**Comment by tseemann** [comment]
I assume you are just running `art` command?

Does it work if you just download the .tgz file from http://www.sanger.ac.uk/science/tools/artemis and run 'art' ?

Does the 'webstart' version work at the above site? (The 'launch' buttons)

**Comment by maculatus** [comment]
Yes, I am using the art command.
I downloaded the tgz file and run art and I got the same problem...same
with the webstar

**Comment by tseemann** [comment]
@maculatus so it sounds like an issue with your computer or Java installation.  I'm not sure there is much we can help with in terms of the Brew project.

**Comment by maculatus** [comment]
Thanks Dr Seemann, We were working with the problem here and we think is
something to do with the VNC server display in the cluster and Java. IT is
hopping to fix the problem today. Yes, it is nothing to do with the brew
system.
Cheers
