### ISSUE TITLE
update jfrog-cli-go error

### ISSUE THREAD

**Issue by Chen-tao** [Homebrew/homebrew-science#3911]
msg as follow:
```
Updated 1 tap (homebrew/core).
==> Updated Formulae
jfrog-cli-go
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'
```

**Comment by ilovezfs** [comment]
brew update again and it shouldn't happen again, right?

**Comment by ilovezfs** [comment]
Oh no, I take that back. This is a third party tap: https://github.com/bramstein/homebrew-webfonttools

You need to bug him to update to sha256.

CC @bramstein

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/brew/issues/606.

**Comment by Chen-tao** [comment]
Got it. 😃
