### ISSUE TITLE
Numpy does not state its dependency on a cython install

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew-science#4163]
This was with `brew install numpy --with-python3 --HEAD`

```
==> python setup.py build --fcompiler=gnu95 --parallel=8 install --prefix=/usr/local/Cellar/numpy/HEAD-a93d9f7 --single-version-externally-managed --record=installed.txt
Running from numpy source directory.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Cython.Compiler.Main
Processing numpy/random/mtrand/mtrand.pyx
Traceback (most recent call last):
  File "/private/tmp/numpy-20160829-65969-143uv2/tools/cythonize.py", line 199, in <module>
    main()
  File "/private/tmp/numpy-20160829-65969-143uv2/tools/cythonize.py", line 195, in main
    find_process_files(root_dir)
```

Running `pip3 install cython` and `pip install cython` fixed the issue.

Is Homebrew capable of doing such a check and/or installing the package in question?

**Comment by dpo** [comment]
This should be reported over at [homebrew/python](https://github.com/Homebrew/homebrew-python/issues).

**Comment by tdsmith** [comment]
This issue was moved to Homebrew/homebrew-python#330
