### ISSUE TITLE
Prokka- Could not determine version of minced 

### ISSUE THREAD

**Issue by brooksph** [Homebrew/homebrew-science#4401]
Installed prokka and upon execution received the following error. 

Exception in thread "main" java.lang.UnsupportedClassVersionError: minced : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[23:07:30] Could not determine version of minced - please install version 1.6 or higher

Ran brew update 
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?

#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/4014e4e35197371981143919fa3e51a4

#### Output of `brew config`:
HOMEBREW_VERSION: 1.0.6
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 35ee2831086e923e7fcaf75fb440b01312e3f9c5
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bd4a5e88436985d05b1e2b5d82b96b02297636ef
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/philliptbrooks/anaconda/bin/python => /Users/philliptbrooks/anaconda/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.8 => /opt/X11

**Comment by jonchang** [comment]
Looks like `minced` needs Java 1.8, but you have 1.6. If you like, you can use Cask to update Java: `brew cask install java`

**Comment by brooksph** [comment]
@jonchang That worked. Thanks!

**Comment by jonchang** [comment]
Glad to hear that. Fixed by #4403.
