### ISSUE TITLE
brew doctor: error in octave.rb

### ISSUE THREAD

**Issue by jarfk6** [Homebrew/homebrew-science#4530]
### Indicate troubleshooting steps taken
- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ X] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:

```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/octave.rb:231: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/octave.rb:237: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/octave.rb:239: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:182:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:236:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1361:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1359:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1359:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:841:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:34:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:34:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```
#### Brief summary of issue:

Running brew update and brew doctor before trying to install pyenv. Brew doctor reported an error and directed me here to report it.
#### The complete command that you issued:

brew update
brew doctor

**Comment by dpo** [comment]
```
cd /usr/local/Library/Taps/homebrew/homebrew-science && git fetch && git reset --hard origin/master
```
