### ISSUE TITLE
Can not install pcl via brew. Failed on install cminpack. (macOS 10.12.2)

### ISSUE THREAD

**Issue by LuZhouheng** [Homebrew/homebrew-science#4749]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

Can not install cminpack via homebrew.

#### Gist with output of `brew doctor`:

**NOTE**: over 7k lines.....

https://gist.github.com/LuZhouheng/79925c40c69c77b9f8e2d857be760d96

### Log

```ruby
$ brew install cminpack
Updating Homebrew...
==> Installing cminpack from homebrew/science
==> Downloading http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.g

curl: (7) Failed to connect to devernay.free.fr port 80: Operation timed out
Error: Failed to download resource "cminpack"
Download failed: http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz
```

```ruby
$ brew install -vd pcl --HEAD --with-openni --with-examples
Updating Homebrew...
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/pcl.rb
==> Installing pcl from homebrew/science
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/eigen.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/flann.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/hdf5.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/szip.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtool.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/cminpack.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/qhull.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libusb.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glew.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/vtk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fontconfig.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/freetype.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libpng.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libtiff.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/openni.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/doxygen.rb
==> Installing dependencies for homebrew/science/pcl: cminpack, libpng, freetype, fontconfig, jpeg, libtiff, vtk, openni
==> Installing homebrew/science/pcl dependency: cminpack
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/cminpack.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
==> Downloading http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz













/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.5 (Macintosh; Intel macOS 10.12.2) curl/7.51.0 http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz -C 0 -o /Users/ChowHungLou/Library/Caches/Homebrew/cminpack-1.3.4.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:27 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:28 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:33 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:34 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:35 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:36 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:37 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:38 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:39 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:40 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:41 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:42 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:43 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:44 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:45 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:46 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:47 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:48 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:49 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:50 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:51 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:52 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:53 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:54 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:55 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:56 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:57 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:58 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:01 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:03 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:04 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:05 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:06 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:07 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:08 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:09 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:10 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:11 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:12 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:13 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0curl: (7) Failed to connect to devernay.free.fr port 80: Operation timed out
Error: Failed to download resource "cminpack"
Download failed: http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:342:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:336:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1868:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1113:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by LuZhouheng** [comment]
It seems like the source of "cminpack" crashed. webcache is here:

http://webcache.googleusercontent.com/search?q=cache:rOfh850tEG0J:devernay.free.fr/hacks/cminpack/+&cd=1&hl=zh-CN&ct=clnk&gl=cn

the source link could not open:

http://devernay.free.fr/hacks/cminpack/cminpack-1.3.4.tar.gz

**Comment by LuZhouheng** [comment]
Fixed by this Issue:

https://github.com/devernay/cminpack/issues/7
