### ISSUE TITLE
R 3.4.0 doesn't compile (--with-openblas --with-x11)

### ISSUE THREAD

**Issue by ReneMalenfant** [Homebrew/homebrew-science#5485]
Typing:
`> brew upgrade r`

Gives the following output:
```
==> Upgrading 1 outdated package, with result:
homebrew/science/r 3.4.0
==> Upgrading homebrew/science/r --with-openblas --with-x11
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
Error: undefined method `set_cpu_flags' for #<Object:0x007f9af28cd248>
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/extend/ENV/shared.rb:258:in `fortran'
/usr/local/Homebrew/Library/Homebrew/requirements/fortran_requirement.rb:8:in `block in <class:FortranRequirement>'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:90:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:90:in `modify_build_environment'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:55:in `call'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:55:in `modify_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:88:in `each'
/usr/local/Homebrew/Library/Homebrew/build.rb:88:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

**Comment by randy3k** [comment]
There is a bug of the homebrew core, try `brew install --env=std r`.
