### ISSUE TITLE
**** Failed to successfully restart the GS3 server.

### ISSUE THREAD

**Issue by mmenon123** [Homebrew/homebrew-science#5895]
I installed GSDL3.08 on redhat7 server. It failed to open gs3server.

User cache dir: /root/.gli/cache/
**** Failed to successfully restart the GS3 server.
AutoLoadConverters: PDFBox Extension to Greenstone detected for PDFPlugin
java.lang.RuntimeException: cannot load system cursor: CopyDrop.32x32
    at sun.awt.X11.XToolkit.lazilyLoadDesktopProperty(XToolkit.java:1437)
    at java.awt.Toolkit.getDesktopProperty(Toolkit.java:1822)
    at java.awt.dnd.DragSource.load(DragSource.java:131)
    at java.awt.dnd.DragSource.<clinit>(DragSource.java:147)
    at org.greenstone.gatherer.gui.tree.DragTree.init(DragTree.java:86)
    at org.greenstone.gatherer.gui.tree.DragTree.<init>(DragTree.java:78)
    at org.greenstone.gatherer.file.WorkspaceTree.<init>(WorkspaceTree.java:55)
    at org.greenstone.gatherer.gui.GatherPane.display(GatherPane.java:219)
    at org.greenstone.gatherer.gui.GUIManager.display(GUIManager.java:401)
    at org.greenstone.gatherer.Gatherer.openGUI(Gatherer.java:663)
    at org.greenstone.gatherer.GathererProg.main(GathererProg.java:81)
Caused by: java.awt.AWTException: Exception: class java.lang.IllegalArgumentException Width (0) and height (0) must be non-zero occurred while creating cursor CopyDrop.32x32
    at java.awt.Cursor.getSystemCustomCursor(Cursor.java:362)
    at sun.awt.X11.XToolkit.lazilyLoadDesktopProperty(XToolkit.java:1435)
    ... 10 more
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.greenstone.gatherer.gui.tree.DragTree.init(DragTree.java:86)
    at org.greenstone.gatherer.gui.tree.DragTree.<init>(DragTree.java:78)
    at org.greenstone.gatherer.file.WorkspaceTree.<init>(WorkspaceTree.java:55)
    at org.greenstone.gatherer.gui.GatherPane.display(GatherPane.java:219)
    at org.greenstone.gatherer.gui.GUIManager.display(GUIManager.java:401)
    at org.greenstone.gatherer.Gatherer.openGUI(Gatherer.java:663)
    at org.greenstone.gatherer.GathererProg.main(GathererProg.java:81)
Caused by: java.lang.RuntimeException: failed to load system cursor: DnD.Cursor.CopyDrop : cannot load system cursor: CopyDrop.32x32
    at java.awt.dnd.DragSource.load(DragSource.java:135)
    at java.awt.dnd.DragSource.<clinit>(DragSource.java:147)
    ... 7 more

Please help me to solve this problem

**Comment by iMichka** [comment]
Hi. This seems to be a bug in openjdk.
See https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1232471
and https://bugs.openjdk.java.net/browse/JDK-8173853

Please update to openjdk 8u152 or 7u161 or java 9 (which is still beta I think).

**Comment by mmenon123** [comment]
I had installed GS3.08 on Server (os: Redhat 7). But Failed to successfully restart the GS3 server.
Here are the details of output after giving this command # ./gli/gli.sh. its out put is shown in Bug #1699965: java.lang.RuntimeException: cannot load system cursor: CopyDrop.32x32

details of lsb_release -a; uname -a; java -version is shown as the following commands
[root@library ~]# lsb -release -a
bash: lsb: command not found...
[root@library ~]# uname -a
Linux library 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016
x86_64 x86_64 x86_64 GNU/Linux
[root@library ~]#
[root@library ~]# java -version
java version "1.7.0_80-ea"
Java(TM) SE Runtime Environment (build 1.7.0_80-ea-b05)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b07, mixed mode)
[root@library ~]# echo $JAVA_HOME
/opt/java/jdk1.7.0_80/bin/java
[root@library ~]# echo $JRE_HOME
/opt/java/jdk1.7.0_80/bin/jre/bin/java
[root@library ~]# echo $PATH
/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin:JAVA_HOME/bin:/root/bin:JAVA_HOME:JRE_HOME:/root/bin


then i tried -X and x11 forqarding

ubuntu@ubuntu-ThinkCentre-M58p ~ $ ssh -X root@server ip...
root@server ip...'s password:
X11 forwarding request failed on channel 0
Last login: Tue Jun 27 10:09:49 2017 from 10.43.12.40
[root@library ~]# gedit /etc/ssh/sshd_config

(gedit:4572): Gtk-WARNING **: cannot open display:

ubuntu@ubuntu-ThinkCentre-M58p ~ $ ssh -Y root@server ip...
rootserver ip...'s password:
X11 forwarding request failed on channel 0
Last login: Tue Jun 27 10:16:20 2017 from own ip
[root@library ~]# export DISPLAY= own ip:0.0
[root@library ~]# echo $DISPLAY
own ip:0.0
[root@library ~]# gedit /etc/ssh/sshd_config

** (gedit:4784): WARNING **: Could not open X display

(gedit:4784): Gtk-WARNING **: cannot open display: own ip:0.0
[root@library ~]# /etc/init.d/sshd reload
-bash: /etc/init.d/sshd: No such file or directory
[root@library ~]# /etc/init.d/sshd
-bash: /etc/init.d/sshd: No such file or directory

Please help me to solve this problem. thanks

**Comment by iMichka** [comment]
You are using java 1.7.0_80-ea
You should be using java 7u161

Really nothing we can do for you. We are just package managers, and provide the tool as-is. If my hints did not help you, you should contact upstream (the GSDL3 developers). Because for the moment there is no proof that your way of packaging GSDL3 breaks it.

**Comment by mmenon123** [comment]
thanks, iMichKa... java now okay

**Comment by mmenon123** [comment]
ubuntu@ubuntu-ThinkCentre-M58p ~ $ ssh -Y root@server ip...
root server ip...'s password:
X11 forwarding request failed on channel 0.
 why happened like this

**Comment by iMichka** [comment]
I have no clue what is wrong. Did you try this (first google hit with your error message):
https://www.cyberciti.biz/faq/how-to-fix-x11-forwarding-request-failed-on-channel-0/

Use vi or nano to edit the file, gedit won`t work.

**Comment by mmenon123** [comment]
Vi/nano editors work fine using ssh, but GUI not works . for enabling that, what to do now?
