### ISSUE TITLE
pymol not using current version of Glew

### ISSUE THREAD

**Issue by 404random** [Homebrew/homebrew-science#6150]
Installed pymol fine but when when trying to open, comes with the following error:

Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 72, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 536, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so, 2): Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.0.0.dylib
  Referenced from: /usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so
  Reason: image not found

After checking the glew version, it seems that I have 2.1 while this is referencing 2.0.0.

**Comment by fxcoudert** [comment]
This will be fixed by #6178
