### ISSUE TITLE
trf fails to install because ldd is run against it

### ISSUE THREAD

**Issue by andrewyatz** [Homebrew/homebrew-science#6183]
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

Command output when trying to install trf

```
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
==> Downloading https://tandem.bu.edu/cgi-bin/trf/trf.download.pl?fileselect=26
Already downloaded: /homes/ensw/.cache/Homebrew/trf-4.07b.pl
==> Verifying trf-4.07b.pl checksum
==> Kept temporary files
Temporary files retained at /tmp/trf-20170822-27515-wp9v02
Error: Failure while executing: [#<Pathname:/nfs/software/ensembl/RHEL7-dev/linuxbrew/opt/glibc/bin/ldd>, "/nfs/software/ensembl/RHEL7-dev/linuxbrew/Cellar/trf/4.07b/bin/trf"]
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/os/linux/elf.rb:58:in `initialize'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/os/linux/elf.rb:99:in `new'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/os/linux/elf.rb:99:in `metadata'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/os/linux/elf.rb:110:in `dynamically_linked_libraries'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:58:in `block in detect_cxx_stdlibs'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:56:in `each'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:56:in `detect_cxx_stdlibs'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/cxxstdlib.rb:26:in `check_compatibility'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb:168:in `detect_stdlibs'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb:154:in `block (2 levels) in install'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/resource.rb:93:in `unpack'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/resource.rb:85:in `stage'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/formula.rb:1884:in `stage'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/formula.rb:1088:in `brew'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb:127:in `block in install'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/utils.rb:556:in `with_env'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb:124:in `install'
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb:201:in `<main>'
```

#### Brief summary of issue:

I tried to install trf from homebrew-science however got this command. Looking at the formula there's no reason to use ldd to link against the binary because it is a perl script. Not sure why it's happening at all to be honest.

#### The complete command that you issued:

`brew install trf`

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/68154ed22e5c6c202daf113a38985797

**Comment by tseemann** [comment]
I get similar.  it's a binary, not source, package.

```
==> Downloading https://tandem.bu.edu/cgi-bin/trf/trf.download.pl?fileselect=26
==> Downloading from http://tandem.bu.edu/trf/downloads/trf407b.linux64
######################################################################## 100.0%
Error: Failure while executing: [#<Pathname:/home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd>, "/home/linuxbrew/.linuxbrew/Cellar/trf/4.07b/bin/trf"]
```

If i run the command manually:

```
/home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd /home/linuxbrew/.linuxbrew/Cellar/trf/4.07b/bin/trf
        linux-vdso.so.1 (0x00007ffe58daa000)
        libm.so.6 => /home/linuxbrew/.linuxbrew/lib/libm.so.6 (0x00007f6620f44000)
        libc.so.6 => /home/linuxbrew/.linuxbrew/lib/libc.so.6 (0x00007f6620b9b000)
        /home/linuxbrew/.linuxbrew/lib/ld.so (0x00007f6621245000)
```

Is this glibc related?

```
/home/linuxbrew/.linuxbrew/Cellar/glibc/2.19_1 (1,359 files, 79.1MB) *
  Poured from bottle on 2017-08-24 at 14:36:12
```

**Comment by sjackman** [comment]
Odd that it fails in `brew install` but is fine when you run it interactively. Can you please report the output of…
```sh
brew sh <<EOF
/home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd /home/linuxbrew/.linuxbrew/Cellar/trf/4.07b/bin/trf
echo $?
EOF
```

**Comment by sjackman** [comment]
Which distribution of Linux are you on, Torsten? Please report the output of `brew config`

**Comment by sjackman** [comment]
Can you please confirm that `brew install hello` works as expected?

**Comment by tseemann** [comment]
within `brew sh` it works fine and returns `0`.

Within the `brew sh` here is the config:
```
HOMEBREW_VERSION: 1.2.6-55-g2139388
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 21393889b8c3e2b8ba6af09c34ceea598292bf16
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 52e06884d31e4c95b59cb0781f5654777525d10b
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 72-core 64-bit haswell
Homebrew Ruby: 2.4.1 => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.1_1/bin/ruby
Clang: 4.0 build
Git: 2.14.1 => /home/linuxbrew/.linuxbrew/bin/git
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.0/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.13_1/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.1_1/bin/ruby
Java: openjdk version "1.8.0_141"
Kernel: Linux 3.10.0-693.1.1.el7.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 7.4 (Maipo) (Maipo)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.19
gcc: 5.3.0
xorg: 20170115
```

Running `brew sh` interactively gives some weird stuff:
```
Your shell has been configured to use Homebrew's build environment;
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit'.
Package bash-completion was not found in the pkg-config search path.
Perhaps you should add the directory containing `bash-completion.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bash-completion' found
bash: /yum: No such file or directory
```

**Comment by andrewyatz** [comment]
Hi. This seems to be working again!

**Comment by tseemann** [comment]
```
==> Downloading https://tandem.bu.edu/cgi-bin/trf/trf.download.pl?fileselect=26
Already downloaded: /home/linuxbrew/.cache/Homebrew/trf-4.07b.pl
```

It seems the server generated the download via CGI and it was broken for a while, and so we got a perl script instead?

BUT if i remove the cached file I still get the problem

```
brew reinstall trf
==> Reinstalling homebrew/science/trf
==> Downloading https://tandem.bu.edu/cgi-bin/trf/trf.download.pl?fileselect=26
==> Downloading from http://tandem.bu.edu/trf/downloads/trf407b.linux64
######################################################################## 100.0%
Error: Failure while executing: [#<Pathname:/home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd>, "/home/linuxbrew/.linuxbrew/Cellar/trf/4.07b/bin/trf"]
```

**Comment by andrewyatz** [comment]
That's really odd. I cleared out my caches and this is my current output

```
brew reinstall -vd trf
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Taps/homebrew/homebrew-science/trf.rb
rm /nfs/software/ensembl/RHEL7-dev/linuxbrew/bin/trf
==> Reinstalling homebrew/science/trf
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Taps/homebrew/homebrew-science/trf.rb
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
==> Downloading https://tandem.bu.edu/cgi-bin/trf/trf.download.pl?fileselect=26
==> Downloading from http://tandem.bu.edu/trf/downloads/trf407b.linux64
/nfs/software/ensembl/RHEL7-dev/linuxbrew/opt/curl/bin/curl --remote-time --location --user-agent Linuxbrew/1.2.6-55-g2139388 (Linux; x86_64 "Red Hat Enterprise Linux Server release 7.2 (Maipo)") curl/7.55.1 --fail http://tandem.bu.edu/trf/downloads/trf407b.linux64 -C 0 -o /homes/ensw/.cache/Homebrew/trf-4.07b.pl.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  109k  100  109k    0     0   109k      0  0:00:01 --:--:--  0:00:01  176k
==> Verifying trf-4.07b.pl checksum
==> Cleaning
Fixing /nfs/software/ensembl/RHEL7-dev/linuxbrew/opt/trf/bin/trf permissions from 644 to 555
==> Finishing up
ln -s ../Cellar/trf/4.07b/bin/trf trf
/nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /nfs/software/ensembl/RHEL7-dev/linuxbrew/Library/Taps/homebrew/homebrew-science/trf.rb
==> Summary
�  /nfs/software/ensembl/RHEL7-dev/linuxbrew/Cellar/trf/4.07b: 3 files, 122.5KB, built in 2 seconds
```

I will say that brew took ages this morning to update. Maybe something has come in upstream not related to this formula that's fixed the issue?

**Comment by sjackman** [comment]
So there was some unexplained weirdness. Is it working now?

**Comment by andrewyatz** [comment]
For me yes

**Comment by tseemann** [comment]
@sjackman No it's still not working for me.
```
brew reinstall trf
==> Reinstalling homebrew/science/trf
==> Downloading https://tandem.bu.edu/cgi-bin/trf/trf.download.pl?fileselect=26
==> Downloading from http://tandem.bu.edu/trf/downloads/trf407b.linux64
######################################################################## 100.0%
Error: Failure while executing: [#<Pathname:/home/linuxbrew/.linuxbrew/opt/glibc/bin/ldd>, "/home/linuxbrew/.linuxbrew/Cellar/trf/4.07b/bin/trf"]
```

**Comment by sjackman** [comment]
I've merged PR https://github.com/Linuxbrew/brew/pull/468 so that you'll get a better error message when `ldd `fails. Can you please `brew update` to `master`, report `brew --version`, and try again? `brew --version` should be `1.3.0-13-g7fa1a1e`

**Comment by tseemann** [comment]
I `brew update` everyday. Is that just Formula. Is there a secret update for the core?
When I  update nothing changes:

```
linuxbrew@trillian:~ $ brew --version
Homebrew 1.2.6-55-g2139388
Homebrew/homebrew-core (git revision b06a7; last commit 2017-08-24)

linuxbrew@trillian:~ $ brew update
Updated Homebrew from 21393889b to 0658f85b1.
Updated 1 tap (homebrew/science).
==> Updated Formulae
homebrew/science/delly            homebrew/science/express ✔        homebrew/science/mothur           homebrew/science/tophat

linuxbrew@trillian:~ $ brew --version
Homebrew 1.2.6-56-g0658f85
Homebrew/homebrew-core (git revision b06a7; last commit 2017-08-24)
```

**Comment by sjackman** [comment]
Sorry, I gave you the wrong version number. 1.3.0 is not released yet. It should have been `Homebrew 1.2.6-56-g0658f85`, so you're up to date.

**Comment by andrewyatz** [comment]
Sorry this has started to fail again for me.

```
$ brew --version
Homebrew >1.2.0 (no git repository)
Homebrew/homebrew-core (git revision b06a; last commit 2017-08-24)
$  brew update
Already up-to-date.
```

Command output is

```bash
$ brew install -v trf
==> Installing trf from homebrew/science
==> Downloading https://tandem.bu.edu/cgi-bin/trf/trf.download.pl?fileselect=26
Already downloaded: /homes/ensw/.cache/Homebrew/trf-4.07b.pl
==> Verifying trf-4.07b.pl checksum
Error: Failure while executing: /nfs/software/ensembl/RHEL7-dev/linuxbrew/opt/glibc/bin/ldd /nfs/software/ensembl/RHEL7-dev/linuxbrew/Cellar/trf/4.07b/bin/trf
/nfs/software/ensembl/RHEL7-dev/linuxbrew/opt/glibc/bin/ldd: line 117: /nfs/software/ensembl/RHEL7-dev/linuxbrew/Cellar/trf/4.07b/bin/trf: Permission denied
```

**Comment by sjackman** [comment]
It looks as though `/nfs/software/ensembl/RHEL7-dev/linuxbrew/Cellar/trf/4.07b/bin/trf: Permission denied` does not have its executable permission bit set.

**Comment by sjackman** [comment]
@andrewyatz If you're handy writing code, try modifying the following line to check whether `path` is executable (`path.executable?`) and if not, do not run `ldd`.
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/os/linux/elf.rb#L57

**Comment by tseemann** [comment]
@andrewyatz 

I've made a new pull request for latest version and solved the problem (not executable).
https://github.com/Homebrew/homebrew-science/pull/6214

You can install now using:
```
brew install -s -v https://raw.githubusercontent.com/tseemann/homebrew-science/86076ba8a2d0ba4fad0837f3c570e705632a0000/trf.rb
```

**Comment by sjackman** [comment]
After installation `brew` sets the executable bit of all ELF files. So I'm not convinced that was the problem. Torsten's PR pointed out that it's downloading a precompiled binary executable. If that binary executable cannot be run by your host system (too old `glibc` or similar problem) then `ldd` may fail, causing this error. Can you see whether that's the problem?
```sh
brew fetch trf
chmod +x ~/.cache/Homebrew/trf-4.07b.pl
file ~/.cache/Homebrew/trf-4.07b.pl
ldd ~/.cache/Homebrew/trf-4.07b.pl
~/.cache/Homebrew/trf-4.07b.pl --version |& head -n2
```

**Comment by tseemann** [comment]
Actually, the TRF download page https://tandem.bu.edu/trf/trf.download.html offers four Linux executables:  { 64bit, 32bit } x { modern, GLIBC<=2.12 }.  I chose 64 bit / modern glibc.

**Comment by sjackman** [comment]
This issue is resolved by PR https://github.com/Linuxbrew/brew/pull/476
See also PR https://github.com/Homebrew/homebrew-science/pull/6214
