### ISSUE TITLE
Error: No available formula with the name "opencv"

### ISSUE THREAD

**Issue by 497256303** [Homebrew/homebrew-science#6471]
**I have this Error today when install opencv in my Mac OS X**
brew install opencv
Error: No available formula with the name "opencv"
Error: 784: unexpected token at '{
<<<<<<< HEAD
  "matplotlib": "homebrew/science",
  "numpy": "homebrew/core",
  "pillow": "homebrew/science",
  "scipy": "homebrew/core"
=======
  "adobe-air-sdk": "caskroom/cask",
  "android-ndk": "caskroom/cask",
  "android-platform-tools": "caskroom/cask",
  "android-sdk": "caskroom/cask",
  "auctex": "homebrew/tex",
  "avidemux": "caskroom/cask",
  "awsenv": "Luzifer/tools",
  "cantera": "homebrew/science",
  "cfitsio": "homebrew/science",
  "cloudfoundry-cli": "pivotal/tap",
  "cmucl": "caskroom/cask",
  "crystax-ndk": "caskroom/cask",
  "corelocationcli": "caskroom/cask",
  "dart": "dart-lang/dart",
  "datamash": "homebrew/science",
  "dgtal": "homebrew/science",
  "dotwrp": "homebrew/science",
  "drush": "homebrew/php",
  "dwarf-fortress": "caskroom/cask",
  "geany": "caskroom/cask",
  "geda-gaf": "homebrew/science",
  "ggobi": "homebrew/science",
  "gimp": "caskroom/cask",
  "grads": "caskroom/cask",
  "gromacs": "homebrew/science",
  "gtkwave": "caskroom/cask",
  "hdf@4": "homebrew/science",
  "hdf5": "homebrew/science",
  "helios": "spotify/public",
  "hexchat": "caskroom/cask",
  "horndis": "caskroom/cask",
  "hwloc": "homebrew/science",
  "inkscape": "caskroom/cask",
  "ipopt": "homebrew/science",
  "itsol": "homebrew/science",
  "jsl": "caskroom/cask",
  "kdiff3": "caskroom/cask",
  "keybase": "caskroom/cask",
  "magit": "dunn/emacs",
  "meld": "caskroom/cask",
  "n98-magerun": "homebrew/php",
  "newick-utils": "homebrew/science",
  "nlopt": "homebrew/science",
  "octave": "homebrew/science",
  "opencv": "homebrew/science",
  "openfst": "homebrew/science",
  "opengrm-ngram": "homebrew/science",
  "osxfuse": "caskroom/cask",
  "pcb": "homebrew/science",
  "pdf-tools": "dunn/emacs",
  "pebble-sdk": "pebble/pebble-sdk",
  "pocl": "homebrew/science",
  "qrupdate": "homebrew/science",
  "quassel": "caskroom/cask",
  "salt": "homebrew/science",
  "shark": "homebrew/science",
  "slicot": "homebrew/science",
  "sqlitebrowser": "caskroom/cask",
  "sundials": "homebrew/science",
  "tetgen": "homebrew/science",
  "ticcutils": "homebrew/science",
  "timbl": "homebrew/science",
  "transmission-remote-gtk": "caskroom/cask/transmission-remote-gui",
  "tuntap": "caskroom/cask",
  "wopr": "homebrew/science"
>>>>>>> elixir 1.5.0-rc.1 (devel) (#15551)
}
'
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:478:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/tap.rb:620:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/missing_formula.rb:95:in `block in tap_migration_reason'
/usr/local/Homebrew/Library/Homebrew/tap.rb:496:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:495:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:495:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:494:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:494:in `each'
/usr/local/Homebrew/Library/Homebrew/missing_formula.rb:94:in `tap_migration_reason'
/usr/local/Homebrew/Library/Homebrew/missing_formula.rb:9:in `reason'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:242:in `rescue in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:91:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Then I use other's suggest to brew tap homebrew/science and brew install opencv
or brew install homebrew/science/opencv
it's the same Error.

Then I use brew install ruby to update my ruby, but it also the same Error and doesn't work.
What should I do?**

**Comment by 497256303** [comment]
Thanks a lot! But there is another Error after I use brew update-reset and then brew install opencv.
Here is the Error.

zby-MBP:~ zby$ brew install homebrew/science/opencv
Updating Homebrew...
Error: No available formula with the name "homebrew/science/opencv"
==> Searching for a previously deleted formula...
Warning: homebrew/science is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/science)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.


zby-MBP:~ zby$ brew tap homebrew/science
zby-MBP:~ zby$ brew install opencv
Error: No available formula with the name "opencv"
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Thanks for helping me!

**Comment by iMichka** [comment]
Opencv was migrated to core. Normally you should be able to install it. Could is see the result of ‘brew config’ and ‘brew doctor’?

**Comment by ilovezfs** [comment]
We took care of it here https://github.com/Homebrew/brew/issues/3502

**Comment by iMichka** [comment]
Nice. Thanks. Didn’t see the cross-posting :)
